ProductCreator As screen:
    OnVisible: |-
        =Set(_eProdNameDef, "");
        Set(_eProdDepDef, "");

    ProductCreatorTitle As label:
        Align: =Align.Center
        Color: =RGBA(151, 0, 0, 1)
        FontWeight: =FontWeight.Bold
        Height: =75
        Size: =25
        Text: |-
            ="Product Creator
            "
        Width: =1366
        ZIndex: =1

    eProdCreatorNameLabel As label:
        Height: =60
        Text: |-
            ="Name:
            "
        X: =20
        Y: =96
        ZIndex: =2

    eProdCreatorDepLabel As label:
        Height: =60
        Text: |-
            ="Department: "
        X: =20
        Y: =156
        ZIndex: =3

    eProdCreatorToHome As icon.BackArrow:
        Color: =RGBA(116, 116, 116, 1)
        Height: =75
        Icon: =Icon.BackArrow
        OnSelect: |-
            =Set(_refresh, false);
            Back();
        PaddingBottom: =16
        PaddingTop: =16
        Width: =75
        X: =1291
        ZIndex: =4

    eProdCreatorNameInput As text:
        BorderColor: =RGBA(151, 0, 0, 1)
        Default: =_eProdNameDef
        Height: =36
        HintText: ="Name"
        HoverBorderColor: =RGBA(151, 0, 0, 1)
        HoverFill: =RGBA(238, 204, 204, 1)
        Width: =1026
        X: =170
        Y: =108
        ZIndex: =5

    eProdCreatorDepInput As text:
        BorderColor: =RGBA(151, 0, 0, 1)
        Default: =_eProdDepDef
        Height: =36
        HintText: ="Department"
        HoverBorderColor: =RGBA(151, 0, 0, 1)
        HoverFill: =RGBA(238, 204, 204, 1)
        Width: =1026
        X: =170
        Y: =168
        ZIndex: =6

    submitNewProduct As icon.Send:
        Color: =RGBA(116, 116, 116, 1)
        Height: =80
        Icon: =Icon.Send
        OnSelect: |-
            =Set(_send, false);
            If(
                Or(
                    IsBlank(eProdCreatorNameInput.Text),
                    IsBlank(eProdCreatorDepInput.Text)
                ),
                Notify("Expected values to be non-empty!", NotificationType.Error);
                false,
                Set(_send, true);
                PostProduct.Run(eProdCreatorNameInput.Text, eProdCreatorDepInput.Text);
                Set(_refresh, true);
                Navigate(ProductPortal);
                Set(_send, false);
                Set(_eProdNameDef, "");
                Set(_eProdDepDef, "");
                Notify("Successfully submitted a product with name " & Char(34) & eProdCreatorNameInput.Text & Char(34) & "!", NotificationType.Success),
                true
            );
        PaddingBottom: =20
        PaddingTop: =20
        Width: =80
        X: =1266
        Y: =668
        ZIndex: =7

    eProdCreateSend As label:
        Align: =Align.Right
        Text: ="Sending..."
        Visible: =_send
        X: =1116
        Y: =688
        ZIndex: =8

