ProductPortal As screen:
    OnVisible: |
        =If(
            _refresh,
            //  Sync    
            Set(_sync, true);
            Clear(ProductCollection);
            If(
                _keepSearch,
                Collect(ProductCollection, SearchProduct.Run(eProdNameInput.Text, eProdDepInput.Text)),
                Collect(ProductCollection, FindAllProducts.Run())
            );
            
            //  Check occurence if needed
            If(
                _doLookup,
                ForAll(
                    ProductCollection,
                    If(
                        ThisRecord.name = _lookupName,
                        Notify("Could not delete product " & Char(34) & _lookupName & Char(34) & "!", NotificationType.Error);
                        Collect(CountCollection, ThisRecord)
                    )
                )
            );
            If(
                And(_doLookup, CountRows(CountCollection) = 0),
                Notify("Successfully deleted product " & Char(34) & _lookupName & Char(34) & "!", NotificationType.Success)
            );
            
            //  Clear variables/collections
            Clear(CountCollection);
            Set(_sync, false);
            Set(_doLookup, false);
            Set(_lookupName, "");
            //Set( _eProdNameSearch, "");
            //Set(_eProdDepSearch, "");
            Set(_refresh, false);
            true,
            true
        );

    ProductPortalTitle As label:
        Align: =Align.Center
        Color: =RGBA(151, 0, 0, 1)
        FontWeight: =FontWeight.Bold
        Height: =75
        Size: =25
        Text: |-
            ="Products Portal
            "
        Width: =970
        ZIndex: =1

    "Products As gallery.'BrowseLayout_Vertical_TwoTextOneImageVariant_ver4.0'":
        Height: =673
        Items: =ProductCollection
        Layout: =Layout.Vertical
        OnSelect: =
        TemplatePadding: =0
        TemplateSize: =111
        Width: =950
        X: =20
        Y: =75
        ZIndex: =2

        eProdNameLabel As label:
            OnSelect: =Select(Parent)
            Text: |-
                ="Name: " & ThisItem.name
            Width: =400
            X: =8
            Y: =15
            ZIndex: =1

        eProdDepartmentLabel As label:
            OnSelect: =Select(Parent)
            Text: |-
                ="Department: " & ThisItem.department
            Width: =400
            X: =8
            Y: =55
            ZIndex: =2

        ProductSeparator As rectangle:
            Fill: =RGBA(116, 116, 116, 1)
            Height: =1
            OnSelect: =Select(Parent)
            Width: =950
            Y: =110
            ZIndex: =3

        RemoveProductIcon As icon.Trash:
            Color: =RGBA(116, 116, 116, 1)
            Height: =80
            Icon: =Icon.Trash
            OnSelect: |-
                =//  Set basic variables
                Set(_lookupName, ThisItem.name);
                Set(_sync, true);
                
                //  Delete product
                DeleteProductByID.Run(UrlParser.Run(ThisItem.uuid).uuid);
                
                //  Sync collection
                Clear(ProductCollection);
                Collect(ProductCollection, FindAllProducts.Run());
                
                //  Check synced collection for occurrence of the item
                ForAll(
                    ProductCollection,
                    If(
                        ThisRecord.name = _lookupName,
                        Notify("Could not delete product " & Char(34) & _lookupName & Char(34) & "!", NotificationType.Error);
                        Collect(CountCollection, ThisRecord)
                    )
                );
                
                If(
                    CountRows(CountCollection) = 0,
                    Notify("Successfully deleted product " & Char(34) & _lookupName & Char(34) & "!", NotificationType.Success)
                );
                
                //  Clear collections/variables
                Clear(CountCollection);
                Set(_lookupName, "");
                Set(_sync, false);
            PaddingBottom: =20
            PaddingTop: =20
            Width: =80
            X: =710
            Y: =15
            ZIndex: =4

        EditProductIcon As icon.Edit:
            Color: =RGBA(116, 116, 116, 1)
            Height: =80
            Icon: =Icon.Edit
            OnSelect: |-
                =Navigate(ProductEditor, None,
                    {
                        edit_name: ThisItem.name,
                        edit_dep: ThisItem.department,
                        edit_uuid: UrlParser.Run(ThisItem.uuid).uuid
                    }
                );
            PaddingBottom: =20
            PaddingTop: =20
            Width: =80
            X: =790
            Y: =15
            ZIndex: =5

        SpecProductIcon As icon.NextArrow:
            Color: =RGBA(116, 116, 116, 1)
            Height: =80
            Icon: =Icon.NextArrow
            OnSelect: |-
                =Navigate(ProductSpecification, None, 
                    {
                        spec_name: ThisItem.name,
                        spec_dep: ThisItem.department,
                        spec_uuid: UrlParser.Run(ThisItem.uuid).uuid
                    }
                );
            PaddingBottom: =20
            PaddingTop: =20
            Width: =80
            X: =870
            Y: =15
            ZIndex: =6

    eProdOptFilter As label:
        Height: =50
        Text: ="Optional Filters"
        Width: =300
        X: =990
        Y: =75
        ZIndex: =3

    eProdNameFilter As label:
        Height: =50
        Text: ="Name"
        Width: =115
        X: =990
        Y: =126
        ZIndex: =4

    eProdNameInput As text:
        BorderColor: =RGBA(151, 0, 0, 1)
        Default: =""
        Height: =35
        HintText: ="Name"
        HoverBorderColor: =RGBA(151, 0, 0, 1)
        HoverFill: =RGBA(238, 204, 204, 1)
        RadiusBottomLeft: =0
        RadiusBottomRight: =0
        RadiusTopLeft: =0
        RadiusTopRight: =0
        Reset: =resetProductName
        Width: =211
        X: =1105
        Y: =133
        ZIndex: =5

    eProdDepFilter As label:
        Height: =50
        Text: ="Department"
        Width: =115
        X: =990
        Y: =176
        ZIndex: =6

    eProdDepInput As text:
        BorderColor: =RGBA(151, 0, 0, 1)
        Default: =""
        Height: =35
        HintText: ="Department"
        HoverBorderColor: =RGBA(151, 0, 0, 1)
        HoverFill: =RGBA(238, 204, 204, 1)
        RadiusBottomLeft: =0
        RadiusBottomRight: =0
        RadiusTopLeft: =0
        RadiusTopRight: =0
        Reset: =resetProductDepartment
        Width: =211
        X: =1105
        Y: =183
        ZIndex: =7

    eProdSyncIcon As icon.Sync:
        Color: =RGBA(116, 116, 116, 1)
        Height: =80
        Icon: =Icon.Sync
        OnSelect: |-
            =Set(_sync, true);
            Clear(ProductCollection);
            If(
                _keepSearch,
                Collect(ProductCollection, SearchProduct.Run(eProdNameInput.Text, eProdDepInput.Text)),
                Collect(ProductCollection, FindAllProducts.Run())
            );
            Set(_sync, false)
        PaddingBottom: =20
        PaddingTop: =20
        Width: =80
        X: =1266
        Y: =668
        ZIndex: =8

    eProdSync As label:
        Align: =Align.Right
        Text: ="Syncing..."
        Visible: =_sync
        X: =1122
        Y: =688
        ZIndex: =9

    eProdToHome As icon.BackArrow:
        Color: =RGBA(116, 116, 116, 1)
        Height: =75
        Icon: =Icon.BackArrow
        OnSelect: =Back()
        PaddingBottom: =16
        PaddingTop: =16
        Width: =75
        X: =1215
        ZIndex: =10

    Icon12 As icon.Add:
        Color: =RGBA(116, 116, 116, 1)
        Height: =80
        Icon: =Icon.Add
        OnSelect: =Navigate(ProductCreator);
        PaddingBottom: =20
        PaddingTop: =20
        Width: =80
        X: =890
        ZIndex: =11

    Icon5 As icon.Home:
        Color: =RGBA(116, 116, 116, 1)
        Height: =75
        Icon: =Icon.Home
        OnSelect: =Navigate(EntitySelector);
        PaddingBottom: =16
        PaddingTop: =16
        Width: =75
        X: =1290
        ZIndex: =12

    Icon6 As icon.Search:
        Color: =RGBA(116, 116, 116, 1)
        Height: =30
        Icon: =Icon.Search
        OnSelect: |-
            =Set(_sync, true);
            Set(_keepSearch, true);
            Clear(ProductCollection);
            Collect(ProductCollection, SearchProduct.Run(eProdNameInput.Text, eProdDepInput.Text));
            Set(_sync, false);
        PaddingBottom: =2
        PaddingTop: =2
        Width: =30
        X: =1284
        Y: =226
        ZIndex: =13

    Icon7_2 As icon.Cancel:
        Color: =RGBA(116, 116, 116, 1)
        Height: =30
        Icon: =Icon.Cancel
        OnSelect: |-
            =UpdateContext({resetProductName: !resetProductName});
            UpdateContext({resetProductName: !resetProductName})
        PaddingBottom: =2
        PaddingTop: =2
        Width: =30
        X: =1326
        Y: =136
        ZIndex: =14

    Icon7_3 As icon.Cancel:
        Color: =RGBA(116, 116, 116, 1)
        Height: =30
        Icon: =Icon.Cancel
        OnSelect: |-
            =UpdateContext({resetProductDepartment: !resetProductDepartment});
            UpdateContext({resetProductDepartment: !resetProductDepartment})
        PaddingBottom: =2
        PaddingTop: =2
        Width: =30
        X: =1326
        Y: =185
        ZIndex: =15

    Icon8 As icon.CancelBadge:
        Color: =RGBA(116, 116, 116, 1)
        Height: =30
        Icon: =Icon.CancelBadge
        OnSelect: |-
            =UpdateContext({resetProductName: !resetProductName});
            UpdateContext({resetProductName: !resetProductName});
            UpdateContext({resetProductDepartment: !resetProductDepartment});
            UpdateContext({resetProductDepartment: !resetProductDepartment});
            Set(_keepSearch, false);
            Set(_sync, true);
            Set(_keepSearch, true);
            Clear(ProductCollection);
            Collect(ProductCollection, FindAllProducts.Run());
            Set(_sync, false);
        PaddingBottom: =2
        PaddingTop: =2
        Width: =30
        X: =1326
        Y: =226
        ZIndex: =16

