ProductSpecification As screen:

    ProductSpecificationTitle As label:
        Align: =Align.Center
        Color: =RGBA(151, 0, 0, 1)
        FontWeight: =FontWeight.Bold
        Height: =75
        Size: =25
        Text: |-
            ="Product Specification
            "
        Width: =1366
        ZIndex: =1

    ProductNameSpec As label:
        Height: =60
        Text: |-
            ="Name: " & name
        Width: =1326
        X: =20
        Y: =96
        ZIndex: =2

    ProductDepartmentSpec As label:
        Height: =60
        Text: |-
            ="Department: " & department
        Width: =1326
        X: =20
        Y: =156
        ZIndex: =3

    eProdToHome_2 As icon.BackArrow:
        Color: =RGBA(116, 116, 116, 1)
        Height: =75
        Icon: =Icon.BackArrow
        OnSelect: =Back();
        PaddingBottom: =16
        PaddingTop: =16
        Width: =75
        X: =1291
        ZIndex: =4

    Label9_2 As label:
        Height: =60
        Text: |-
            ="UUID: " & uuid
        Width: =1326
        X: =20
        Y: =216
        ZIndex: =5

    RemoveProductSpecItem As icon.Trash:
        Color: =RGBA(116, 116, 116, 1)
        Height: =80
        Icon: =Icon.Trash
        OnSelect: |-
            =Navigate(ProductPortal);
            Set(_sync, true);
            DeleteProductByID.Run(uuid);
            Clear(ProductCollection);
            Collect(ProductCollection, FindAllProducts.Run());
            Set(_sync, false);
        PaddingBottom: =20
        PaddingTop: =20
        Width: =80
        X: =1266
        Y: =668
        ZIndex: =6

    EditProductSpecItem As icon.Edit:
        Color: =RGBA(116, 116, 116, 1)
        Height: =80
        Icon: =Icon.Edit
        OnSelect: |-
            =Navigate(ProductEditor, {name: name, department: department, uuid: uuid});
        PaddingBottom: =20
        PaddingTop: =20
        Width: =80
        X: =1186
        Y: =668
        ZIndex: =7

